### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by tisgotos** [PKU-DAIR/Hetu-Galvatron#4]
How can I use Galvatron to train my custom models like Vision Transformer (ViT) and Convolutional Neural Network (CNN)?

**Comment by Fizzmy** [comment]
Thank you for your interest! Unfortunately, Galvatron does not support parallelism strategy search for CNN models because they are not transformer-based. Additionally, CNN models typically don't require mixed parallelism strategies due to their smaller scale. Galvatron previously supported ViT models, but we are currently adding many new features to the system that haven't yet been adapted for ViT. We plan to address this soon!
